### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Ruben Serra",
    "company": "Rubotic",
    "address": "Dirección postal aleatoria",
    "phone": "003400000000",
    "email": "e@e.com",
    "password": "password1235"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "e@e.com",
    "password": "password2"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZS5jb20iLCJpYXQiOjE2NTM5ODMzNjYsImV4cCI6MTY1Mzk4NDI2Nn0.JLRX4bw_ifmuTO9Tyd9UV1Mx4ZRkXOuEPpzUWb8NhnU

### Get Refresh Token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiZUBlLmNvbSIsImlhdCI6MTY1Mzk5MTgyNywiZXhwIjoxNjU2NTgzODI3fQ.9Ky2L8rJ9H5gty8xS6KXqHkbh7l0HqCxpNR5cwSkB-0

###Reset Password
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "e@e.com"
}

### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "e@e.com",
    "pin": 464592,
    "newPassword": "password2"
}

### User Logout endopoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZS5jb20iLCJpYXQiOjE2NTQyNDIxMjIsImV4cCI6MTY1NDI0MzAyMn0.kodaDxlAEyKCajul2FIlpMkM4_LSf97hm7FR8P8OXB0

### 