### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Ruben Serra",
    "company": "Rubotic",
    "address": "Dirección postal aleatoria",
    "phone": "003400000000",
    "email": "e@e.com",
    "password": "password1235"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "e@e.com",
    "password": "password1235"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZS5jb20iLCJpYXQiOjE2NTM4Mzk2NzQsImV4cCI6MTY1Mzg0MDU3NH0.aeoMEyvdFkURkyYKtgbqdoyuSblUJ6dzxigjyw1nhyE